### ISSUE TITLE
Use latest `firehose-core`

### ISSUE THREAD

**Issue by maoueh** [starknet-graph/firehose-starknet#6]
We have updated `firehose-core` recently with some newer feature and data model and I would like if we could find a way to upgrade `firehose-starknet` to use it.

`firehose-core` also gain a one-size-fits-all binary `firecore` that could even replace the need for a specific `firestark` binary. I've updated `firehose-acme` last week to use latest `firehose-core` version https://github.com/streamingfast/firehose-acme/commit/b03c6d41c28f6678279240f17e564c99dac50ed4.

One thing is that the node's integration needs to also change to use the new Firehose chain-agnostic data exchange protocol, see:
- [`INIT` format](https://github.com/streamingfast/dummy-blockchain/commit/3fea13d19d61d115e5de26207f91d686a3ebd266#diff-b3b2463e03a1b44fc488ccebb6c2a91d304caf4f442a150c7996975f4190bbe7R48-R56)
- [`BLOCK` format](https://github.com/streamingfast/dummy-blockchain/commit/3fea13d19d61d115e5de26207f91d686a3ebd266#diff-b3b2463e03a1b44fc488ccebb6c2a91d304caf4f442a150c7996975f4190bbe7R31-R56)

**Comment by xJonathanLEI** [comment]
Hi @maoueh, it's been a while. I just updated this repo to use the latest `firehose-core` version of v1.3.3 with https://github.com/starknet-graph/firehose-starknet/commit/4b46637d197954f0eb6c23b103b264954ce3d015.

The upgrade is pretty much just a version bump + error resolution though. It does not take advantage of the built-in binary. (Is any integration actually using it? I just checked `firehose-ethereum` and it looks like it still has its own `main`?)

As for the new `INIT` and `BLOCK` format, is this a requirement now to be integrated into the graph network? I can work on these next.

**Comment by maoueh** [comment]
> The upgrade is pretty much just a version bump + error resolution though. It does not take advantage of the built-in binary. (Is any integration actually using it? I just checked firehose-ethereum and it looks like it still has its own main?)

We support both now. Network that requires indexes though needs to use the library integration version, which you have now so all good.

> As for the new INIT and BLOCK format, is this a requirement now to be integrated into the graph network? I can work on these next.

It's not a strict requirement, but yes we suggest to use the new format from now on. If you still have a chain's specific console reader and don't want to move away just now, it's ok. The library will have a way to provide a custom console reader implementation for the mid-term future anyway.

We are working on migrating Ethereum to use this new model exclusively, but it will take some time to have roll out to every chain supported.

Closing.
